"""event idempotency key nullable=True

Revision ID: 5294d7754d24
Revises: a9e264639448
Create Date: 2026-07-23 18:08:25.414986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5294d7754d24'
down_revision: Union[str, Sequence[str], None] = 'a9e264639448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'idempotency_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'idempotency_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
