"""make idempotency_key not null

Revision ID: d24c592cf6b2
Revises: 5294d7754d24
Create Date: 2026-08-14 14:12:59.025056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd24c592cf6b2'
down_revision: Union[str, Sequence[str], None] = '5294d7754d24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'idempotency_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'idempotency_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
